api:
  enabled: true
  address: "127.0.0.1:8686"

sources:
  netflow_prod:
    type: netflow
    address: "0.0.0.0:9995"
    protocols: ["ipfix", "netflow_v9", "netflow_v5", "sflow"]
    include_raw_data: false  # Disable raw data to reduce memory usage
    drop_events_without_templates: true  # Drop events when no template is available
    max_field_length: 512  # Limit field values to 512 bytes
    max_templates: 100  # Reduce from 1000 to limit memory usage
    template_timeout_secs: 1800  # Reduce to 30 minutes
    max_length: 8192  # Limit packet size to reduce memory usage

sinks:
  console:
    type: console
    inputs: ["netflow_prod"]
    encoding:
      codec: json 