# Example configuration demonstrating varint framing for protobuf
# This is compatible with tools like ClickHouse that use protobuf with varint length prefixes

# Source configuration with varint framing
sources:
  protobuf_source:
    type: socket
    mode: tcp
    address: "0.0.0.0:8080"
    decoding:
      codec: protobuf
      protobuf:
        desc_file: "path/to/your/protobuf.desc"
        message_type: "your.package.MessageType"
    framing:
      method: varint_length_delimited

# Alternative: using the default framing (varint is now default for protobuf)
sources:
  protobuf_source_default:
    type: socket
    mode: tcp
    address: "0.0.0.0:8081"
    decoding:
      codec: protobuf
      protobuf:
        desc_file: "path/to/your/protobuf.desc"
        message_type: "your.package.MessageType"
    # No framing specified - will use varint_length_delimited by default

# Sink configuration with explicit varint framing
sinks:
  protobuf_sink:
    type: socket
    mode: tcp
    address: "localhost:9090"
    encoding:
      codec: protobuf
      protobuf:
        desc_file: "path/to/your/protobuf.desc"
        message_type: "your.package.MessageType"
    framing:
      method: varint_length_delimited

# Alternative: using the default framing (varint is now default for protobuf)
sinks:
  protobuf_sink_default:
    type: socket
    mode: tcp
    address: "localhost:9091"
    encoding:
      codec: protobuf
      protobuf:
        desc_file: "path/to/your/protobuf.desc"
        message_type: "your.package.MessageType"
    # No framing specified - will use varint_length_delimited by default

# Complete pipeline example
sources:
  input:
    type: socket
    mode: tcp
    address: "0.0.0.0:8080"
    decoding:
      codec: protobuf
      protobuf:
        desc_file: "input.desc"
        message_type: "input.Message"
    framing:
      method: varint_length_delimited

sinks:
  output:
    type: socket
    mode: tcp
    address: "localhost:9090"
    encoding:
      codec: protobuf
      protobuf:
        desc_file: "output.desc"
        message_type: "output.Message"
    framing:
      method: varint_length_delimited

# Connect source to sink
topology:
  sources:
    - input
  sinks:
    - output
  edges:
    - input -> output 